version: "3.9"
services:
  ecomm:
    image: ecomm:1.0
    container_name: newecomm
    networks:
      - compose-bridge

  mongo-ecomm:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
    - type: bind
      source: C:\Users\n134415\OneDrive - Santander Office 365\Documentos\projetos-github\ecomm/mongo
      target: /mongo-scripts
    # volumes:
    #   - C:\mongo:/etc/data

networks:
  compose-bridge:
    driver: bridge