version: "3.9"
services:
  ecomm:
    image: ecomm:3.0
    container_name: newecomm
    build: '.'
    depends_on:
      - mongo-ecomm
    links:
      - mongo-ecomm
    ports:
      - 3000:3000
    networks:
      - compose-bridge

  mongo-ecomm:
    image: mongo
    container_name: ecomm-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
    - db-mong-ecomm:/data/db
    - type: bind
      source: C:\Users\n134415\Documents\projetos-github\ecomm\mongo
      target: /mongo-scripts
    networks:
      - compose-bridge

networks:
  compose-bridge:
    driver: bridge

volumes:
  db-mong-ecomm: